### ISSUE TITLE
my more complete emacs-direnv package

### ISSUE THREAD

**Issue by wbolster** [jml/direnv-el#3]
hi,

for a while i used a few elisp snippets for emacs direnv integration. until very recently i did not bother to polish those, so the code was sitting semi-functional on my local disk. i recently decided to clean it up and make a proper emacs package for it, which i just published here:

https://github.com/wbolster/emacs-direnv

i wanted to register it on melpa but it turned out you have beaten me to it. :)

however, since my package actually works (unlike yours), and since it is more robust and more feature complete (see my readme), would it be okay with you if i took over the `direnv` name on melpa?

you can become my first user which would save you from fixing your own package :)

alternatively, we could work together and merge my package into yours, but as far as i can see my package is a superset of yours feature-wise, and it seems my implementation is also a bit more robust and has (arguably) cleaner code.

my main goal is to have `package-install direnv` give a _good_ user experience for all potential users, which is currently not the case. since we've clearly both suffered from the same itch and both decided to scratch it, let's make sure others have a smoother experience when it comes to direnv and emacs. :)

if you're busy with others things that is totally understandable, just give a comment on this issue that "it is fine that @wbolster takes over" and i will handle the melpa transition without bothering you.

thanks in advance for your reply, and keep up the good work!

/cc @nkoguro @shlevy @jml

**Comment by jml** [comment]
> since my package actually works (unlike yours)

Bold words.

Nevertheless, you no doubt are better qualified as a maintainer than I. "it is fine that @wbolster takes over".

**Comment by wbolster** [comment]
hi @jml, thanks for the reply!

>> since my package actually works (unlike yours)

> Bold words.

oops, sorry, i didn't mean to offend you. as you hopefully noticed i tried hard to make my original report friendly...

please let me explain. the reason i wrote that is best explained in #2, from which i concluded that this package has been broken for at least 5 months, so i assumed you did not use it yourself anymore. and since that pr went unanswered for a while, i figured you lost interest and moved on. which is totally fine btw, it happens to my own side projects all the time. ;)

anyway, i'll make direnv on melpa work again.
